theme: minima

title: Solution Assurance Process Vision Global
author: Katarina Nikolic
email: kn250140@ncr.com
description: 
  Vision System Management improvement program, we are instituting a mandatory requirement 
  to apply the Solution Assurance Process for all new Vision opportunities regardless of size. 
  Vision projects will also be tracked and reported to leadership going forward. 


