theme: minima

title: Solution Assurance Process Vision Global
author: Katarina Nikolic
email: kn250140@ncr.com
description: 
  Vision System Management improvement program, we are instituting a mandatory requirement 
  to apply the Solution Assurance Process for all new Vision opportunities regardless of size. 
  Vision projects will also be tracked and reported to leadership going forward. 

# social links
twitter_username: [Global Vision Projects and Forms](https://ncr.sharepoint.com/sites/VisionGlobalCoEPSTeam/SitePages/Vision-Global-Projects-and-Forms.aspx).
github_username:  [Vision System Management Improvement Program](https://ncr.sharepoint.com/sites/VisionGlobalCoEPSTeam/SitePages/Vision-Global-Projects-and-Forms.aspx).

show_excerpts: true # Vision System Management Improvement Program
